### ISSUE TITLE
Update dockerhub images with log4j fix

### ISSUE THREAD

**Issue by wkobryn** [GerritCodeReview/k8s-gerrit#14]
Would it be possible to update gerrit images on dockerhub to 3.3.10, 3.4.4 and 3.5.1 versions released recently (that contain the reload4j replacement of log4j) ?
It's not a problem of building that myself and updating values.yaml with private registry, but I'd like rather to use the official images...

**Comment by thomasdraebing** [comment]
A change updating Gerrit was pushed here: https://gerrit-review.googlesource.com/c/k8s-gerrit/+/335156. As soon as it got reviewed and submitted, I will updatet he images on Dockerhub.

However, note that Gerrit is not affected by the kog4j vulnerability: https://www.gerritcodereview.com/2021-12-13-log4j-statement.html
