### ISSUE TITLE
healthcheck.jar url is wrong

### ISSUE THREAD

**Issue by git9am** [GerritCodeReview/k8s-gerrit#23]
In ./container-images/gerrit-base/Dockerfile it downloads healthcheck.jar from

https://gerrit-ci.gerritforge.com/view/Plugins-stable-3.6/job/plugin-healthcheck-bazel-master-stable-3.6/lastSuccessfulBuild/artifact/bazel-bin/plugins/healthcheck/healthcheck.jar

But it should be 

https://gerrit-ci.gerritforge.com/view/Plugins-stable-3.6/job/plugin-healthcheck-bazel-stable-3.5-stable-3.6/lastSuccessfulBuild/artifact/bazel-bin/plugins/healthcheck/healthcheck.jar

**Comment by thomasdraebing** [comment]
Fixed in https://gerrit-review.googlesource.com/c/k8s-gerrit/+/373894
