### ISSUE TITLE
Update docker images to use gerrit 3.3.0

### ISSUE THREAD

**Issue by Venthe** [GerritCodeReview/k8s-gerrit#5]
Currently K8S helm charts use 3.1.7; there is no possibility to use rest api for labels for example

I've actually have changed the code, so after I verify it I might request pull; if that's okay. Please note, that i've just swapped version in dockerfile, and I've not checked it at all with gerrit replica.

**Comment by thomasdraebing** [comment]
Hi @Venthe,

I have a change in review updating to 3.2.5.1: https://gerrit-review.googlesource.com/c/k8s-gerrit/+/281807.
I will update that change to use 3.3.0.

Best,
Thomas

**Comment by Venthe** [comment]
I think I've done more than this.. .:)

https://gerrit-review.googlesource.com/c/k8s-gerrit/+/290492

Of course, I'll be happy to discuss it more 'there'

**Comment by Venthe** [comment]
Gerrit is already updated to 3.3.1
